"
Exception raised when you want to name/rename a chest (resp. an object in a chest) when another chest (resp. another object in the same chest) is already named so.
"
Class {
	#name : 'ChestKeyAlreadyInUseError',
	#superclass : 'Error',
	#category : 'Chest-Errors',
	#package : 'Chest',
	#tag : 'Errors'
}
